apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      hostNetwork: true
      securityContext:
        fsGroup: 1000
      containers:
        - name: server
          image: itzg/minecraft-server:java21
          ports:
            - containerPort: 25565
              name: minecraft
          
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "PAPER"
            - name: MEMORY
              value: "4G"
            - name: OPS
              value: "waywardb0und"
            - name: SEED
              value: "109405673854"

          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "5Gi"
              cpu: "2000m"
          
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /data/server.properties
              subPath: server.properties
            - name: config
              mountPath: /data/ops.json
              subPath: ops.json
          
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
      
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mc-data
        - name: config
          configMap:
            name: mc-config