apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: standard  # Uncomment and set to your storage class if needed