apiVersion: v1
kind: Service
metadata:
  name: mc
  namespace: games
spec:
  type: NodePort
  selector:
    app: mc
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32565